name: ui_kit
description: Design UI kit
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.6
  lottie: 2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.4
  flutter_gen_runner: 5.3.1
  linters:
    path: ../linters

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/lottie/
  fonts:
    - family: Work Sans
      fonts:
        - asset: assets/fonts/WorkSans-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/WorkSans-VariableFont_wght.ttf
flutter_gen:
  output: lib/src/assets/
  line_length: 100
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      class_name: UiKitAssets

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: true