arb-dir: lib/l10n
template-arb-file: app_ru.arb
output-localization-file: app_localizations.dart
output-dir: lib/src/
synthetic-package: false
nullable-getter: false
untranslated-messages-file: untranslated_messages.txt